[build]
  command = "npm run build"
  publish = "dist"

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
[[headers]]
  for = "/*.webp"
  [headers.values]
  cache-control = '''
  public, max-age=31536000, s-max-age=86400,
  '''