[build]
  command = "pnpm run build"
  publish = "dist"

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
[[headers]]
  for = "/_astro/*"
  [headers.values]
  cache-control = '''
  public, max-age=604800, s-max-age=86400, immutable
  '''

[[headers]]
  for = "/*.svg"
  [headers.values]
  cache-control = '''
  public, max-age=604800, s-max-age=86400, immutable
  '''
