name: Check URLs with Lychee

on:
  push:
  pull_request:
  schedule:
    # Run everyday at 3 am UTC
    - cron: "0 3 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      # Cache lychee results (e.g. to avoid hitting rate limits)
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      # check URLs with Lychee
      - uses: actions/checkout@v4

      - name: Lychee URL checker
        uses: lycheeverse/lychee-action@v1
        with:
          # arguments with file types to check
          args: >-
            --base 'https://docs.awesomebible.de/'
            --cache
            --verbose
            --no-progress
            './**/*.md'
            './**/*.html'
          # fail the action on broken links
          fail: true
        env:
          # to be used in case rate limits are surpassed
          GITHUB_TOKEN: ${{secrets.gh_token}}
